name: ${project.name}
version: ${project.version}
main: me.frauenfelderflorian.wuprojects.WUProjects
api-version: 1.18
depend: [ WorldUtils ]
authors: [ flopsi_ ]
description: ${project.description}
commands:
  allitems:
    description: collect all obtainable items
    usage: /<command> start | skip | reset
